notifications:
  email: false
language:
- cpp
os:
- linux
- osx
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenal-dev
    - libjpeg-dev
    - libudev-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libvorbis-dev
    - libflac-dev
    - gcc-5
    - g++-5
install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-5"; fi
- git clone https://github.com/SFML/SFML.git
- cd SFML
- curl https://gitlab.peach-bun.com/pinion/SFML/commit/3383b4a472f0bd16a8161fb8760cd3e6333f1782.patch
  | patch -p1
- mkdir install
- mkdir build
- cd build
- cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_INSTALL_FRAMEWORK_PREFIX=../install
  -DSFML_BUILD_FRAMEWORKS=FALSE -DBUILD_SHARED_LIBS=TRUE ..
- make
- make install
- cd ../../
script:
- mkdir install/
- mkdir install/SmallGameEngine
- cmake -DCMAKE_INSTALL_PREFIX=./install/SmallGameEngine -DSFML_ROOT=./SFML/install -DCMAKE_MODULE_PATH=./SFML/cmake/Modules .
- make
- make install
before_deploy:
  - zip SmallGameEngine-$TRAVIS_OS_NAME ./install/SmallGameEngine/ -r
  - ls # To check the zip file is created correctly
deploy:
  release: SmallGameEngine
  description: 'SmallGameEngine master branch release'
  skip_cleanup: true
  provider: releases
  api_key:
    secure: n5YYrvLk5Ft1l7lPmJtLHeS6CzP9Ug76cpuG57EzDFatUHa376mwi2US3eevImQ9I09KFtcFOFpqSphEvyvtIVhMsGkhm89kJn/inSmBOkmWWasN/m2chDTic0SnfoiwbYozIfqCJ5PIW+nRgwGY65np4GInnixcfaK5giaGBrI=
  file: SmallGameEngine-$TRAVIS_OS_NAME.zip
  on:
    tags: true
